data:
  path: "data/winequality-red.csv"
  test_size: 0.2
  random_state: 42

model:
  name: "random_forest"
  params:
    n_estimators: 100
    max_depth: 10
    random_state: 42

mlflow:
  tracking_uri: "mlruns"
  experiment_name: "wine_quality"