name: ML Pipeline CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ml-pipeline:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        make install
        
    - name: Lint code
      run: |
        make lint
        
    - name: Run tests
      run: |
        make test
        
    - name: Download dataset
      run: |
        mkdir -p data
        wget -O data/winequality.csv https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv
        
    - name: Train model
      run: |
        make train
        
    - name: Upload ML model artifact
      uses: actions/upload-artifact@v3
      with:
        name: ml-model
        path: mlruns/
        retention-days: 7